### PR TITLE
Refactoring the codebase 👨‍🔧

### LINKED ISSUE #1: Update and refactor the codebases
Navbar desktop on bigger screen is too high.

found that it's using `height: 14vh;`

### PR DESCRIPTION
**Pull request by ilhambara**
Update, configure, and everything in between.

- [x] resolved #1

### CODE REVIEW

**Comment by ilhambara** [comment]
update: navbar components

**Comment by ilhambara** [comment]
update (sections):
- hero
- moments
- activities

**Comment by ilhambara** [comment]
update: 

- footer
- fix spacing in /developers

**Review by ofc-xtra — APPROVED** [review]
Good Job!

**Pull request merged**
